apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  template:
    spec:
      nodeSelector:
        node-role.backend: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  template:
    spec:
      nodeSelector:
        node-role.backend: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sso-service
spec:
  template:
    spec:
      nodeSelector:
        node-role.backend: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: organization-service
spec:
  template:
    spec:
      nodeSelector:
        node-role.backend: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-service
spec:
  template:
    spec:
      nodeSelector:
        node-role.backend: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  template:
    spec:
      nodeSelector:
        node-role.backend: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-service
spec:
  template:
    spec:
      nodeSelector:
        node-role.backend: "true"
