apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wms

labels:
  - pairs:
      app.kubernetes.io/part-of: wms
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
    includeTemplates: true

resources:
  - 00-namespace.yaml
  - 01-storage.yaml
  - 02-secrets.yaml
  - 02-configmaps.yaml
  - 03-databases.yaml
  - 04-backend.yaml
  - 05-infrastructure.yaml
  - 06-ingress.yaml
  - 07-autoscaling.yaml
  - 08-network-policies.yaml
  - 09-frontend.yaml
  - 10-backend-common-env.yaml

patchesStrategicMerge:
  - patches/backend-node-selectors.yaml
  - patches/frontend-node-selector.yaml
  - patches/infrastructure-node-selectors.yaml
